// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uscftlkkhhrpkukhkqxt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVzY2Z0bGtraGhycGt1a2hrcXh0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyODY0NjksImV4cCI6MjA3Mjg2MjQ2OX0.dcFbDLDuoAKwOUQEdo08G3zJwLzvsGCpQ8UonHCNsto";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});